### ISSUE TITLE
When restoring a task from a savepoint, tables that were previously synchronized but later deleted still exist in a state

### ISSUE THREAD

**Issue by zhangkunjie** [apache/flink-cdc#3462]
1、I configured MySQL tables A and B to synchronize to a pipeline in Starrocks using the configuration file yaml Task.
2、I use the flink savepoint command to save the running task as a _metadata.
3、I modified the yaml configuration file by commenting out Table B, leaving only Table A, and then restoring the task from the second step's savepoint. At this point, the synchronization task only synchronizes Table A, which is not a problem.
4、At this point, I used the flink savepoint command again to save the running task as a _metadata. Through observation, it was found that the information of Table B, which had already been deleted, still exists in the _metadata at this time. Why does the deleted B table information still exist in the _metadata?

**Comment by zhangkunjie** [comment]
1. I configured MySQL tables A and B to synchronize to a pipeline in Starrocks using the configuration file yaml? Task.
2. I use the flink savepoint command to save the running task as a _metadata.
3. I modified the yaml configuration file by commenting out Table B, leaving only Table A, and then restoring the task from the second step's savepoint. At this point, the synchronization task only synchronizes Table A, which is not a problem.
4. At this point, I used the flink savepoint command again to save the running task as a _metadata. Through observation, it was found that the information of Table B, which had already been deleted, still exists in the _metadata at this time. Why does the deleted B table information still exist in the _metadata?

**Comment by leonardBang** [comment]
As required by Apache Flink, please report bugs or new features on [Apache Jira](https://issues.apache.org/jira)
under the project Flink using component tag Flink CDC. You must have a JIRA account in order to log cases and issues.
If you don’t have an ASF JIRA account, you can request one at the [ASF Self-serve portal](https://selfserve.apache.org/jira-account.html),
account creation requires review by the PMC member of the application project, which normally takes one to two working days to be approved.

你好，缺陷和新功能需要在 [Apache Jira](https://issues.apache.org/jira) 或 Flink 邮件列表（[dev@flink.apache.org](mailto:dev@flink.apache.org)）中反馈，而不是在这里创建新 issue。 GitHub 上的新 issue 会被忽略且自动关闭。
